name: Java CI with Maven
on:
  schedule:
    - cron: '0 1 * * *'  # 每天 UTC 时间 1 点执行（北京时间 9 点）
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8.0.382+5'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        env:
          OWNER_REPO: ${{secrets.OWNER_REPO}}
          CAI_MO_GU_TOKEN: ${{secrets.CAI_MO_GU_TOKEN}}
          MY_GITHUB_API_TOKEN: ${{secrets.MY_GITHUB_API_TOKEN}}
        run: mvn -B -q package --file pom.xml  # 打包生成 JAR
      - name: Run Java program  # 新增步骤：运行 JAR 文件
        env:  # 传递环境变量给 Java 程序
          OWNER_REPO: ${{secrets.OWNER_REPO}}
          CAI_MO_GU_TOKEN: ${{secrets.CAI_MO_GU_TOKEN}}
          MY_GITHUB_API_TOKEN: ${{secrets.MY_GITHUB_API_TOKEN}}
        run: java -jar target/caimogu_task-1.0-SNAPSHOT.jar  # 执行 JAR
